name: first

on: push

jobs: 
        job1:
                name: First Job
                runs-on: windows-latest
                steps:
                - name: step1
                  uses: actions/checkout@v2
                - name: step2
                  uses: "Get-ChildItem Env | Sort-Object Name"
        job2:
                name: Second Job
                runs-on: ubuntu-latest
                steps:
                - name: step1
                  uses: actions/checkout@v2
                - name: step2
                  run: env | sort
                        
